### ISSUE TITLE
Addition of testbeam-related topics / intro

### ISSUE THREAD

**Issue by leloup314** [SiLab-Bonn/silab-bonn.github.io#12]
A nice intro to what is testbeam (potentially with a pic of telescope at e.g. DESY) and the respective topic description @cbespin

**Comment by cbespin** [comment]
#13 adds the topic introduction

**Comment by leloup314** [comment]
Very nice, thanky. Can you add the two changes I requested? They are needed for the markdown rendering

**Comment by leloup314** [comment]
#14 closes this bad boy
