### ISSUE TITLE
Add modification date for each topic

### ISSUE THREAD

**Issue by leloup314** [SiLab-Bonn/silab-bonn.github.io#4]
Add the sites build date as "last modified" date and show this in header on generated gh-page

**Comment by leloup314** [comment]
Does [this](https://silab-bonn.github.io/) look good to you or do you want to manually add a date for each topic @BothoP ?

**Comment by BothoP** [comment]
It's already a nice addition. I would still prefer an update per project since the updates usually do not coincide.

**Comment by leloup314** [comment]
I agree. To do so, one needs a better understanding of how [Jekyll](https://jekyllrb.com/docs/) builds `gh-pages`. I guess the solution is to split the topics into `pages` and use the `page.date` variable. For now, this commit (20250e62f1799012b36cd2b21d823e3f8b2bb15d) should be enough. Maybe @Giakou has already looked into this? 😉

**Comment by leloup314** [comment]
Unfortunately, an already existing `Jekyll` plugin, called [`jekyll-last-modified-at`](https://github.com/gjtorikian/jekyll-last-modified-at) does **not** work with `gh-pages` (see https://github.com/gjtorikian/jekyll-last-modified-at/issues/32). A possible workaround, which requires manually adding dates to each file, can be found [here](https://tomkadwill.com/adding-last-modified-date-to-jekyll).
