### ISSUE TITLE
Review BELLE 2 topics / intro

### ISSUE THREAD

**Issue by leloup314** [SiLab-Bonn/silab-bonn.github.io#6]
Please review the [Belle 2-related topic](https://github.com/SiLab-Bonn/silab-bonn.github.io/tree/master/topics/belle_2.md) as well as the contents of the [introduction to the Belle 2 project](https://github.com/SiLab-Bonn/silab-bonn.github.io/tree/master/intros/belle_2.md)

**Comment by leloup314** [comment]
How does it look? Just quick review if topics are still relevant or anything new is coming? Doesn't take more than 30 mins ;)

**Comment by leloup314** [comment]
I removed the old topics from Belle 2 due to no response in this issue. If you would like to add something again, please open a PR. Tomorrow, topics are being discussed in the SLHC meeting

**Comment by Giakou** [comment]
Sorry for the late reply @leloup314, I was mostly on vacation in the meantime. As far as I know we do not have concrete topics for theses yet and we would also like to have maximum one Bachelor/Master student at a time (a new Bachelor student just started today). Thanks for removing the old topics and I/we will open a PR once we have something more concrete.
