### ISSUE TITLE
Review DMAPS topics / intro

### ISSUE THREAD

**Issue by leloup314** [SiLab-Bonn/silab-bonn.github.io#7]
Please review the [DMAPS-related topic](https://github.com/SiLab-Bonn/silab-bonn.github.io/tree/master/topics/dmaps.md) as well as the contents of the [introduction to the DMAPS project](https://github.com/SiLab-Bonn/silab-bonn.github.io/tree/master/intros/dmaps.md)
@cbespin @idcs0906 @ Lars

**Comment by cbespin** [comment]
If I understood correctly we will discuss proposals in the next SLHC meeting, right?
I also have some ideas outside of DMAPS.

**Comment by leloup314** [comment]
IMHO you can just add whatever you have right now. If the topics outside DMAPS don't fit into any of the other project, just add a new one to the intro as well. My plan is to have the page ready for next SLHC meeting so we can discuss the topics which are listed on the page.

**Comment by leloup314** [comment]
There is currently only one DMAPS topic, is this still valid? Is there anything to add? If not I can update the entry myself @lschall @idcs0906 @cbespin
