### ISSUE TITLE
Review of sensor design / characterization-related topics / intro

### ISSUE THREAD

**Issue by leloup314** [SiLab-Bonn/silab-bonn.github.io#8]
Please review the [sensor-related topic](https://github.com/SiLab-Bonn/silab-bonn.github.io/tree/master/topics/sensor_development.md) as well as the contents of the [introduction to the sensor development section](https://github.com/SiLab-Bonn/silab-bonn.github.io/tree/master/intros/sensor_development.md)

**Comment by themperek** [comment]
Add #10 

[introduction to the sensor development section](https://github.com/SiLab-Bonn/silab-bonn.github.io/tree/master/intros/sensor_development.md) looks  OK. One can do some more exciting but is OK.

**Comment by leloup314** [comment]
You can always add some more exciting stuff ;) @SinuoZhang is the guard ring stuff still valid?

**Comment by SinuoZhang** [comment]
> You can always add some more exciting stuff ;) @SinuoZhang is the guard ring stuff still valid?

not valid anymore. I'm thinking about a simulation for inter-pixel isolation structure, Beam/Radioactive source measurement for inter-pixel isolation test. No concrete plan yet :(

**Comment by leloup314** [comment]
Okay, then you can remove this topic and add a new one, doesn't have to be too concrete yet. I want to have the possible topics gathered until next SLHC meeting so we can discuss them

**Comment by leloup314** [comment]
#10 closes this
